#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{ define "eric-esoa-topology-handling.labels" }}
app.kubernetes.io/name: {{ template "eric-esoa-topology-handling.name" . }}
app.kubernetes.io/version: {{ template "eric-esoa-topology-handling.version" . }}
app.kubernetes.io/instance: {{ .Release.Name | quote }}
app: {{ template "eric-esoa-topology-handling.name" . }}
chart: {{ template "eric-esoa-topology-handling.chart" . }}
release: {{ .Release.Name | quote }}
heritage: {{ .Release.Service | quote }}
{{- end}}
