#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{ if .Values.ingress.tls.th }}
{{- if and .Values.ingress.tls.th.key .Values.ingress.tls.th.certificate }}
{{ $name := printf "%s" .Values.ingress.tls.secretName }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $name }}
{{- if not $secret }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secretName | quote }}
  labels:
  {{- include "eric-esoa-topology-handling.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-esoa-topology-handling.helm-annotations" .| nindent 4 }}
type: kubernetes.io/tls
data:
  tls.key: {{ .Values.ingress.tls.th.key | b64enc }}
  tls.crt: {{ .Values.ingress.tls.th.certificate | b64enc }}
{{- end }}
{{- end }}
{{- end }}
