#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{ $name := printf "%s" (include "eric-esoa-topology-handling.name" .) }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $name) }}
{{- if not $secret }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "eric-esoa-topology-handling.name" . }}
  labels:
  {{- include "eric-esoa-topology-handling.kubernetes-io-info" .| nindent 4 }}
  bam-global-cm: nil
  annotations:
  {{- include "eric-esoa-topology-handling.helm-annotations" .| nindent 4 }}
    "helm.sh/resource-policy": keep
    "helm.sh/hook": pre-install, pre-upgrade
type: Opaque
data:
  application.user: {{ default (randAlphaNum 10) .Values.credentials.applicationUser | b64enc | quote }}
  application.password: {{ default (randAlphaNum 10) .Values.credentials.applicationPassword | b64enc | quote }}
  management.user: {{ default (randAlphaNum 10) .Values.credentials.managementUser | b64enc | quote }}
  management.password: {{ default (randAlphaNum 10) .Values.credentials.managementPassword | b64enc | quote }}
  platform.schema: {{ default (randAlphaNum 10) .Values.credentials.platformSchema | b64enc | quote }}
  platform.password: {{ default (randAlphaNum 10) .Values.credentials.platformPassword | b64enc | quote }}
  regional.schema: {{ default (randAlphaNum 10) .Values.credentials.regionalSchema | b64enc | quote }}
  regional.password: {{ default (randAlphaNum 10) .Values.credentials.regionalPassword | b64enc | quote }}
  artemis.user: {{ default (randAlphaNum 10) .Values.credentials.artemisUser | b64enc | quote }}
  artemis.password: {{ default (randAlphaNum 10) .Values.credentials.artemisPassword | b64enc | quote }}
  artemis.clusterUser: {{ default (randAlphaNum 10) .Values.credentials.artemisClusterUser | b64enc | quote }}
  artemis.clusterPassword: {{ default (randAlphaNum 10) .Values.credentials.artemisClusterPassword | b64enc | quote }}
{{- end }}
