#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{ if .Values.certificates.enabled }}
{{ if .Values.certificates.ca.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "eric-esoa-topology-handling.name" . }}-root-issuer
  labels:
    {{- include "eric-esoa-topology-handling.kubernetes-io-info" .| nindent 4 }}
  annotations:
    {{- include "eric-esoa-topology-handling.helm-annotations" .| nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
{{- end }}