#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{ if .Values.global.networkPolicy.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "eric-esoa-topology-handling.name" . }}-cts-artemis-policy
  labels:
  {{- include "eric-esoa-topology-handling.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-esoa-topology-handling.helm-annotations" .| nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: eric-oss-jms-svc-amq
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: eric-oss-jms-svc-amq
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: eric-oss-cmn-topology-svc-core
        - podSelector:
            matchLabels:
              app: eric-pm-server
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: eric-oss-topo-trouble-mngmt-ui
{{- end }}
